#!/usr/bin/env python3.6
import getpass
import string
import uuid
import random
from user import User
from credential import Credential

def create_user(username,password):
    '''
    function to create  new user
    '''
    new_user= User(username,password)
    return new_user
    
def save_user(user):
    '''
    function to save new user
    '''
    User.save_user()
        
def delete_user(user):
    '''
    function that deletes a user
    '''
    User.delete_user() 
        
def find_user(username):
    '''
    function that finds a user
    '''
    return User.find_by_username( username)
    
def check_existing_users(username):
    '''
    function that checks if a user exist
    '''
    return User.user_exist(username)
    
def display_all_users():
    '''
    function that returns all the saved users in the application
    '''
    return User.user.display_all_users()

def main():
    print("This is an application that helps you manage your credentials")
    print(" What is your name please?")
    name = input()

    enquire = input(f"{name}, Do you have a twitter account? yes or no > ")

    if enquire== "no":
        print("create an account")
        username = input("Enter username > ")
        create = input(
            f"{username}, Do you want autogenerated password? yes or no > ")
        if create == "no":
            print("create your password then")
            getpass.getpass()
            print("Successfully logged in")

        while True:
            print("""
            Use the short codes: cc to create new credential
                                 dc to display credentials
                                 fc to find credential
                                 dl to delete credential
                                 gp to generate random password
                                 ex to exit
                                 """)
            short_code = input("Navigate now using the short-codes > ")

            if short_code == "cc":
                print("Create new account")
                print("-"*12)

                print("Enter your name(s)")
                name = input("> ")

                print("Enter account for example twitter.....")
                account = input("> ")

                print("Enter your preffered username")
                username = input("> ")

                print("Enter password")
                password = ("> ")

                save_credential(create_credential(
                    name, account, username, password))

                print("\n")
                print(
                    f"New credential Nam:{name}, account:{account}, and password:{password} have been created")
                print("\n")

            elif short_code == "gp":
                print("Please enter the account you wantto generate password for > ")
                account = input("Enter accounttype > ")

                def random_password(string_length):
                    letters = string.ascii_letters
                    return "".join(random.choice(letters) for i in range(string_length))

                print(
                    f"Your password for {account} is: ", random_password(10))

            elif short_code == "dc":

                if display_credentials():
                    print("Credentials and passwords")
                    for credential in display_credentials():
                        print(
                            f"Name:{credential.name} Account:{credential.account} Username:{credential.username} Password:{password}.")
                        print("\n")
                else:
                    print(
                        "No credentials")
                    print("\n")

            elif short_code == 'fc':

                print("Enter the username to search")

                search_username = input()
                if check_existing_credentials(search_username):
                    search_credential = find_credential(search_username)
                    print(
                        f"{search_credential.account} {search_credential.username}")
                    print('-' * 25)

                    print(f"Account password {search_credential.password}")

                else:
                    print("Does not exist")

            elif short_code == "dl":
                print("Enter username to delete.")
                my_delete = input("> ")
                my_del = find_credential(my_delete)
                delete_credential(my_del)
                print(
                    f" Credential with {my_delete} has been moved to trash successfully")

            elif short_code == "ex":
                print("Logged out")
                break

    elif ask == "yes":
        print("Please enter your username and password to login")
        username = input("Username > ")
        # account_password = getpass.getpass()


if __name__ == '__main__':
    main()